CREATE TABLE IF NOT EXISTS "dummy" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value TEXT UNIQUE default gen_random_uuid(),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

insert into "dummy" default values;