CREATE TABLE IF NOT EXISTS "ability" (
    id_ability    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(50) UNIQUE NOT NULL,
    record_status SMALLINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "university" (
    id_university BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) NOT NULL,
    id_country    BIGINT REFERENCES "country"(id_country),
    record_status SMALLINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    modified_at   TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "degree" (
    id_degree     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) UNIQUE NOT NULL,
    record_status SMALLINT NOT NULL,
    id_language   BIGINT REFERENCES "language"(id_language),
    id_university BIGINT REFERENCES "university"(id_university),
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    modified_at   TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "domain" (
    id_domain     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100) UNIQUE NOT NULL,
    record_status SMALLINT NOT NULL,
    id_language   BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "groups" (
    id_group      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) UNIQUE NOT NULL,
    record_status SMALLINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    modified_at   TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "professional_skill" (
    id_personal_skill        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR(255) UNIQUE NOT NULL,
    record_status            SMALLINT NOT NULL,
    id_language              BIGINT REFERENCES "language"(id_language),
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    modified_at              TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "sub_group" (
    id_sub_group  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) UNIQUE NOT NULL,
    record_status SMALLINT NOT NULL,
    id_group      BIGINT REFERENCES "groups"(id_group)
);

CREATE TABLE IF NOT EXISTS "sub_group_ability" (
    ability_id  BIGINT NOT NULL REFERENCES "ability"(id_ability),
    sub_group_id BIGINT NOT NULL REFERENCES "sub_group"(id_sub_group)
);

CREATE TABLE users (
    id_user       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname     VARCHAR(255) NOT NULL,
    lastname      VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(255),
    email         VARCHAR(255) UNIQUE NOT NULL,
    password      TEXT NOT NULL,
    description   TEXT,
    record_status SMALLINT NOT NULL,
    id_domain     BIGINT REFERENCES "domain"(id_domain),
    id_country    BIGINT REFERENCES "country"(id_country),
    id_language   BIGINT NOT NULL REFERENCES "language"(id_language),
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    modified_at   TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "user_degree" (
    id_degree BIGINT NOT NULL REFERENCES "degree"(id_degree),
    id_user   BIGINT NOT NULL REFERENCES "users"(id_user)
);

CREATE TABLE IF NOT EXISTS "user_professional_skill" (
    id_personal_skill BIGINT NOT NULL REFERENCES "professional_skill"(id_personal_skill),
    id_user           BIGINT NOT NULL REFERENCES "users"(id_user)
);

CREATE TABLE IF NOT EXISTS "user_sub_group" (
    id_user      BIGINT NOT NULL REFERENCES "users"(id_user),
    id_sub_group BIGINT NOT NULL REFERENCES "sub_group"(id_sub_group)
);

CREATE TABLE IF NOT EXISTS "pending_user_registration" (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname  VARCHAR(255) NOT NULL,
    lastname   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    password   TEXT NOT NULL,
    otp        VARCHAR(255) NOT NULL,
    id_language BIGINT NOT NULL REFERENCES "language"(id_language),
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "refresh_token" (
    id_refresh_token BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user          BIGINT NOT NULL UNIQUE REFERENCES "users"(id_user),
    expires_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    token            TEXT NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    modified_at      TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "forgot_password_request" (
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email             VARCHAR(255) UNIQUE NOT NULL,
    verification_code VARCHAR(255) NOT NULL,
    expiration        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "mail_change_request" (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user    BIGINT NOT NULL REFERENCES "users"(id_user),
    token      TEXT NOT NULL UNIQUE,
    expiration TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);