CREATE TABLE IF NOT EXISTS "appointment_request" (
    id_appointment_request BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_at                 TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    timezone               VARCHAR(255) NOT NULL,
    status                 SMALLINT NOT NULL,
    id_user                BIGINT REFERENCES "users"(id_user),
    title                  VARCHAR(255) NOT NULL,
    description            VARCHAR(255) NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "slot" (
    id_slot            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    google_calendar_id VARCHAR(255) NOT NULL UNIQUE,
    start_at           TIMESTAMP WITHOUT TIME ZONE,
    end_at             TIMESTAMP WITHOUT TIME ZONE,
    timezone           VARCHAR(255) NOT NULL,
    id_user            BIGINT REFERENCES "users"(id_user),
    record_status SMALLINT NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
