CREATE ROLE app WITH LOGIN PASSWORD 'hjra0yvwWw';
CREATE ROLE payment_user WITH LOGIN PASSWORD '6DCuU6355e';
CREATE ROLE reader WITH LOGIN PASSWORD 'aOu81Fii2H';
CREATE ROLE regular_user WITH LOGIN PASSWORD 'MP0YosUMYQ';

GRANT CONNECT ON DATABASE coltip_db TO app;
GRANT CONNECT ON DATABASE coltip_db TO payment_user;
GRANT CONNECT ON DATABASE coltip_db TO reader;
GRANT CONNECT ON DATABASE coltip_db TO regular_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO app;
GRANT ALL PRIVILEGES ON DATABASE coltip_db TO app;
--GRANT ALL PRIVILEGES ON TABLE payment_information TO app;
GRANT ALL PRIVILEGES ON TABLE course_payment_history TO app;
GRANT ALL PRIVILEGES ON TABLE payment_category TO app;
GRANT ALL PRIVILEGES ON TABLE payment_mode TO app;
GRANT ALL PRIVILEGES ON TABLE ability TO app;
GRANT ALL PRIVILEGES ON TABLE admin_ability TO app;
GRANT ALL PRIVILEGES ON TABLE "admin" TO app;
GRANT ALL PRIVILEGES ON TABLE group_ability TO app;
GRANT ALL PRIVILEGES ON TABLE groups TO app;
GRANT ALL PRIVILEGES ON TABLE sub_group TO app;
GRANT ALL PRIVILEGES ON TABLE users TO app;
GRANT ALL PRIVILEGES ON TABLE user_ability TO app;
GRANT ALL PRIVILEGES ON TABLE user_password_history TO app;
GRANT ALL PRIVILEGES ON TABLE course TO app;
GRANT ALL PRIVILEGES ON TABLE course_progress TO app;
GRANT ALL PRIVILEGES ON TABLE course_enrollment TO app;
GRANT ALL PRIVILEGES ON TABLE authentication_history TO app;
GRANT ALL PRIVILEGES ON TABLE professional_skill TO app;
GRANT ALL PRIVILEGES ON TABLE user_professional_skill TO app;
GRANT ALL PRIVILEGES ON TABLE country TO app;
GRANT ALL PRIVILEGES ON TABLE "language" TO app;
GRANT ALL PRIVILEGES ON TABLE "domain" TO app;
GRANT ALL PRIVILEGES ON TABLE degree TO app;
GRANT ALL PRIVILEGES ON TABLE university TO app;
GRANT ALL PRIVILEGES ON TABLE course_type TO app;
GRANT ALL PRIVILEGES ON TABLE certificate TO app;

--ALTER TABLE payment_information OWNER TO payment_user;
ALTER TABLE course_payment_history OWNER TO payment_user;
ALTER TABLE payment_category OWNER TO payment_user;
ALTER TABLE payment_mode OWNER TO payment_user;

GRANT ALL PRIVILEGES ON TABLE ability TO regular_user;
GRANT ALL PRIVILEGES ON TABLE admin_ability TO regular_user;
GRANT ALL PRIVILEGES ON TABLE "admin" TO regular_user;
GRANT ALL PRIVILEGES ON TABLE group_ability TO regular_user;
GRANT ALL PRIVILEGES ON TABLE groups TO regular_user;
GRANT ALL PRIVILEGES ON TABLE sub_group TO regular_user;
GRANT ALL PRIVILEGES ON TABLE users TO regular_user;
GRANT ALL PRIVILEGES ON TABLE user_ability TO regular_user;
GRANT ALL PRIVILEGES ON TABLE user_password_history TO regular_user;
GRANT ALL PRIVILEGES ON TABLE course TO regular_user;
GRANT ALL PRIVILEGES ON TABLE course_progress TO regular_user;
GRANT ALL PRIVILEGES ON TABLE course_enrollment TO regular_user;
GRANT ALL PRIVILEGES ON TABLE authentication_history TO regular_user;
GRANT ALL PRIVILEGES ON TABLE professional_skill TO regular_user;
GRANT ALL PRIVILEGES ON TABLE user_professional_skill TO regular_user;
GRANT ALL PRIVILEGES ON TABLE country TO regular_user;
GRANT ALL PRIVILEGES ON TABLE "language" TO regular_user;
GRANT ALL PRIVILEGES ON TABLE "domain" TO regular_user;
GRANT ALL PRIVILEGES ON TABLE degree TO regular_user;
GRANT ALL PRIVILEGES ON TABLE university TO regular_user;
GRANT ALL PRIVILEGES ON TABLE course_type TO regular_user;
GRANT ALL PRIVILEGES ON TABLE certificate TO regular_user;

GRANT SELECT ON TABLE ability TO regular_user;
GRANT SELECT ON TABLE admin_ability TO regular_user;
GRANT SELECT ON TABLE "admin" TO regular_user;
GRANT SELECT ON TABLE group_ability TO regular_user;
GRANT SELECT ON TABLE groups TO regular_user;
GRANT SELECT ON TABLE sub_group TO regular_user;
GRANT SELECT ON TABLE users TO regular_user;
GRANT SELECT ON TABLE user_ability TO regular_user;
GRANT SELECT ON TABLE user_password_history TO regular_user;
GRANT SELECT ON TABLE course TO regular_user;
GRANT SELECT ON TABLE course_progress TO regular_user;
GRANT SELECT ON TABLE course_enrollment TO regular_user;
GRANT SELECT ON TABLE authentication_history TO regular_user;
GRANT SELECT ON TABLE professional_skill TO regular_user;
GRANT SELECT ON TABLE user_professional_skill TO regular_user;
GRANT SELECT ON TABLE country TO regular_user;
GRANT SELECT ON TABLE "language" TO regular_user;
GRANT SELECT ON TABLE "domain" TO regular_user;
GRANT SELECT ON TABLE degree TO regular_user;
GRANT SELECT ON TABLE university TO regular_user;
GRANT SELECT ON TABLE course_type TO regular_user;
GRANT SELECT ON TABLE certificate TO regular_user;

--GRANT REFERENCES ON TABLE payment_information TO regular_user;
GRANT REFERENCES ON TABLE course_payment_history TO regular_user;
GRANT REFERENCES ON TABLE payment_category TO regular_user;
GRANT REFERENCES ON TABLE payment_mode TO regular_user;

--GRANT SELECT ON TABLE payment_information TO reader;
GRANT SELECT ON TABLE course_payment_history TO reader;
GRANT SELECT ON TABLE payment_category TO reader;
GRANT SELECT ON TABLE payment_mode TO reader;
GRANT SELECT ON TABLE ability TO reader;
GRANT SELECT ON TABLE admin_ability TO reader;
GRANT SELECT ON TABLE "admin" TO reader;
GRANT SELECT ON TABLE group_ability TO reader;
GRANT SELECT ON TABLE groups TO reader;
GRANT SELECT ON TABLE sub_group TO reader;
GRANT SELECT ON TABLE users TO reader;
GRANT SELECT ON TABLE user_ability TO reader;
GRANT SELECT ON TABLE user_password_history TO reader;
GRANT SELECT ON TABLE course TO reader;
GRANT SELECT ON TABLE course_progress TO reader;
GRANT SELECT ON TABLE course_enrollment TO reader;
GRANT SELECT ON TABLE authentication_history TO reader;
GRANT SELECT ON TABLE professional_skill TO reader;
GRANT SELECT ON TABLE user_professional_skill TO reader;
GRANT SELECT ON TABLE country TO reader;
GRANT SELECT ON TABLE "language" TO reader;
GRANT SELECT ON TABLE "domain" TO reader;
GRANT SELECT ON TABLE degree TO reader;
GRANT SELECT ON TABLE university TO reader;
GRANT SELECT ON TABLE course_type TO reader;
GRANT SELECT ON TABLE certificate TO reader;