# Spring
logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=f3301a47230a96bf531a5faf8a8c7e044109495d5e961cbc3c011bbe0716e4a9

# Admin config
coltip.mailing.no_reply=noreply@coltip.com
coltip.admin.mail=admin@example.com

# Google calendar
google.calendar.enable=false

# Mailing
spring.mail.host=coltip_email
spring.mail.port=1025
spring.mail.protocol=smtp
spring.mail.test-connection=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.auth=false