spring.application.name=coltip

spring.profiles.validate=true

# Every HTTP Rest endpoints will start with /api
server.servlet.context-path=/api

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# OTP
coltip.otp.length=6
## 10 minutes
coltip.otp.expiration_ms=600000

# Db connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

## JWT
jwt.expiration=3600000