# JWT
jwt.secret=${JWT_SECRET}

# Google calendar
google.calendar.id=${GOOGLE_CALENDAR_ID}

# Admin config
coltip.mailing.no_reply=noreply@coltip.com
coltip.admin.mail=${ADMIN_EMAIL}

# Mailing
spring.mail.port=${COLTIP_MAILER_PORT}
spring.mail.protocol=smtp
spring.mail.host=${COLTIP_MAILER_HOST}
spring.mail.username=${COLTIP_MAILER_USERNAME}
spring.mail.password=${COLTIP_MAILER_PASSWORD}
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=true
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
