# PostgreSQL Database Connection Configuration
spring.datasource.url=jdbc:postgresql://coltip_db:5432/coltip_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#Hikary Configuration
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.maximumPoolSize=10

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.boot=DEBUG

#Context
server.servlet.context-path=/coltip

#e-mail
spring.mail.host=coltip_email
spring.mail.port=1025
spring.mail.username=
spring.mail.password=