# PostgreSQL Database Connection Configuration
#spring.datasource.url=jdbc:postgresql://coltip_db:5432/coltip_db
#spring.datasource.username=postgres
#spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true


#Hikari Configuration
#spring.datasource.hikari.connectionTimeout=20000
#spring.datasource.hikari.idleTimeout=30000
#spring.datasource.hikari.maxLifetime=2000000
#spring.datasource.hikari.maximumPoolSize=10

#Context
server.servlet.context-path=/coltip

#Port
server.port=8081

# JWT Configuration
jwt.expiration=3600000
jwt.secret=f3301a47230a96bf531a5faf8a8c7e044109495d5e961cbc3c011bbe0716e4a9

# Refresh token expiration
refresh.token.expiration=1000000000

spring.security.filter.order=10

# Flyway Configuration
spring.flyway.enabled=false
#spring.flyway.url=jdbc:postgresql://coltip_db:5432/coltip_db
#spring.flyway.user=postgres
#spring.flyway.password=admin
#spring.flyway.locations=classpath:db/migration
#spring.flyway.clean-disabled=false

# otp configuration
sign.up.otp.length=6
sign.up.otp.expiration=600000

# email configuration
spring.mail.host=coltip_db
spring.mail.port=8025
#spring.mail.username=ca652ac508b9dd
#spring.mail.password=bde78293169918
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

db.user.general=app
db.user.flyway=postgres
path.to.database=jdbc:postgresql://coltip_db:5432/coltip_db
driver.to.database=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://coltip_db:5432/coltip_db
spring.datasource.username=postgres
spring.datasource.password=admin

flyway.datasource.url=jdbc:postgresql://coltip_db:5432/coltip_db
flyway.datasource.username=postgres
flyway.datasource.password=admin

#VAULT CONFIG
#spring.cloud.vault.uri = http://coltip_db:8300
#spring.cloud.vault.token=hvs.jRyZhgmtxJqVqavnrfGFQMqk
#spring.cloud.vault.kv.enabled=true
#spring.cloud.vault.kv.backend=secret