--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-03-06 22:05:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 33467)
-- Name: ability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ability (
    id_ability integer NOT NULL,
    record_status integer,
    ability_name character varying(50)
);


ALTER TABLE public.ability OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33466)
-- Name: ability_id_ability_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ability ALTER COLUMN id_ability ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ability_id_ability_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 33473)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id_admin integer NOT NULL,
    password character varying(64),
    username character varying(100)
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 33478)
-- Name: admin_ability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_ability (
    ability_id integer NOT NULL,
    admin_id integer NOT NULL
);


ALTER TABLE public.admin_ability OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 33472)
-- Name: admin_id_admin_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN id_admin ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_admin_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 33482)
-- Name: authentication_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_history (
    authentication_status integer,
    id_authentication_history integer NOT NULL,
    id_user integer,
    date_authentication timestamp(6) without time zone
);


ALTER TABLE public.authentication_history OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 33481)
-- Name: authentication_history_id_authentication_history_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_history ALTER COLUMN id_authentication_history ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_history_id_authentication_history_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33488)
-- Name: certificate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.certificate (
    id_certificate integer NOT NULL,
    id_course integer,
    id_user integer,
    content character varying(1000)
);


ALTER TABLE public.certificate OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 33487)
-- Name: certificate_id_certificate_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.certificate ALTER COLUMN id_certificate ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificate_id_certificate_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 33496)
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id_admin integer,
    id_country integer NOT NULL,
    id_language integer,
    origin_id_country integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    country_name character varying(100)
);


ALTER TABLE public.country OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 33495)
-- Name: country_id_country_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id_country ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_country_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 33502)
-- Name: course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course (
    id_admin integer,
    id_course integer NOT NULL,
    id_course_type integer,
    id_language integer,
    origin_id_course integer,
    price double precision,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    course_title character varying(100),
    photo character varying(1000),
    description character varying(30000)
);


ALTER TABLE public.course OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 33510)
-- Name: course_enrollment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_enrollment (
    id_course integer,
    id_course_enrollment integer NOT NULL,
    id_payment_mode integer,
    id_user integer,
    record_status integer,
    total_paid double precision
);


ALTER TABLE public.course_enrollment OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 33509)
-- Name: course_enrollment_id_course_enrollment_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_enrollment ALTER COLUMN id_course_enrollment ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_enrollment_id_course_enrollment_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 33501)
-- Name: course_id_course_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course ALTER COLUMN id_course ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_course_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 33516)
-- Name: course_payment_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_payment_history (
    amount_paid double precision,
    id_payment_history integer NOT NULL,
    id_payment_mode integer,
    id_user integer,
    record_status integer,
    payment_date timestamp(6) without time zone
);


ALTER TABLE public.course_payment_history OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 33515)
-- Name: course_payment_history_id_payment_history_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_payment_history ALTER COLUMN id_payment_history ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_payment_history_id_payment_history_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 33522)
-- Name: course_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_progress (
    completion_level double precision,
    id_course integer,
    id_course_progress integer NOT NULL,
    id_user integer
);


ALTER TABLE public.course_progress OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 33521)
-- Name: course_progress_id_course_progress_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_progress ALTER COLUMN id_course_progress ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_progress_id_course_progress_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 33528)
-- Name: course_step; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_step (
    id_admin integer,
    id_course integer,
    id_course_step integer NOT NULL,
    id_language integer,
    origin_id_course_step integer,
    record_status integer,
    step_order integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    file_content character varying(1000),
    description character varying(30000)
);


ALTER TABLE public.course_step OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 33527)
-- Name: course_step_id_course_step_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_step ALTER COLUMN id_course_step ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_step_id_course_step_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 33536)
-- Name: course_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_type (
    id_admin integer,
    id_course_type integer NOT NULL,
    id_language integer,
    origin_id_course_type integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    course_type_name character varying(100)
);


ALTER TABLE public.course_type OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 33535)
-- Name: course_type_id_course_type_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_type ALTER COLUMN id_course_type ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_type_id_course_type_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 33542)
-- Name: degree; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.degree (
    id_admin integer,
    id_degree integer NOT NULL,
    id_language integer,
    id_university integer,
    origin_id_degree integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    degree_name character varying(100)
);


ALTER TABLE public.degree OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 33541)
-- Name: degree_id_degree_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.degree ALTER COLUMN id_degree ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.degree_id_degree_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 33548)
-- Name: domain; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.domain (
    id_admin integer,
    id_domain integer NOT NULL,
    id_language integer,
    origin_id_domain integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    domain_name character varying(100)
);


ALTER TABLE public.domain OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 33547)
-- Name: domain_id_domain_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.domain ALTER COLUMN id_domain ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_id_domain_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 33553)
-- Name: group_ability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_ability (
    ability_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.group_ability OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 33557)
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
    id_group integer NOT NULL,
    record_status integer,
    group_name character varying(100)
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 33556)
-- Name: groups_id_group_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.groups ALTER COLUMN id_group ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_group_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 33563)
-- Name: language; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.language (
    id_language integer NOT NULL,
    language_code character varying(2),
    language_name character varying(85)
);


ALTER TABLE public.language OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 33562)
-- Name: language_id_language_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.language ALTER COLUMN id_language ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_id_language_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 33569)
-- Name: payment_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_category (
    id_admin integer,
    id_language integer,
    id_payment_category integer NOT NULL,
    origin_id_payment_category integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    category_name character varying(100)
);


ALTER TABLE public.payment_category OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 33568)
-- Name: payment_category_id_payment_category_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_category ALTER COLUMN id_payment_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_category_id_payment_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 33575)
-- Name: payment_mode; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_mode (
    id_admin integer,
    id_language integer,
    id_payment_category integer,
    id_payment_mode integer NOT NULL,
    origin_id_payment_mode integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    mode_code character varying(50),
    mode_name character varying(255)
);


ALTER TABLE public.payment_mode OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 33574)
-- Name: payment_mode_id_payment_mode_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_mode ALTER COLUMN id_payment_mode ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_mode_id_payment_mode_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 33581)
-- Name: professional_skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.professional_skill (
    id_admin integer,
    id_language integer,
    id_personal_skill integer NOT NULL,
    origin_id_personal_skill integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    skill_name character varying(100)
);


ALTER TABLE public.professional_skill OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 33580)
-- Name: professional_skill_id_personal_skill_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.professional_skill ALTER COLUMN id_personal_skill ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professional_skill_id_personal_skill_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 25133)
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id integer NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    token character varying(255),
    user_id integer NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25132)
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.refresh_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.refresh_token_id_seq OWNER TO postgres;

--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 217
-- Name: refresh_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.refresh_token_id_seq OWNED BY public.refresh_token.id;


--
-- TOC entry 258 (class 1259 OID 33587)
-- Name: sub_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sub_group (
    id_group integer,
    id_sub_group integer NOT NULL,
    record_status integer,
    sub_group_name character varying(100)
);


ALTER TABLE public.sub_group OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 33586)
-- Name: sub_group_id_sub_group_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sub_group ALTER COLUMN id_sub_group ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_group_id_sub_group_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 33593)
-- Name: university; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.university (
    country integer,
    id_admin integer,
    id_university integer NOT NULL,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    university_name character varying(100)
);


ALTER TABLE public.university OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 33592)
-- Name: university_id_university_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.university ALTER COLUMN id_university ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.university_id_university_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 33598)
-- Name: user_ability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_ability (
    id_ability integer NOT NULL,
    id_user integer NOT NULL
);


ALTER TABLE public.user_ability OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 33601)
-- Name: user_degree; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_degree (
    id_degree integer NOT NULL,
    id_user integer NOT NULL
);


ALTER TABLE public.user_degree OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 33605)
-- Name: user_password_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_password_history (
    id_user integer,
    id_user_password_history integer NOT NULL,
    date_added_to_history timestamp(6) without time zone,
    password character varying(255)
);


ALTER TABLE public.user_password_history OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 33604)
-- Name: user_password_history_id_user_password_history_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_password_history ALTER COLUMN id_user_password_history ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_password_history_id_user_password_history_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 33610)
-- Name: user_professional_skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_professional_skill (
    id_personal_skill integer NOT NULL,
    id_user integer NOT NULL
);


ALTER TABLE public.user_professional_skill OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 34093)
-- Name: user_sub_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_sub_group (
    id_user integer NOT NULL,
    id_sub_group integer NOT NULL
);


ALTER TABLE public.user_sub_group OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 33614)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_admin integer,
    id_country integer,
    id_domain integer,
    id_language integer,
    id_user integer NOT NULL,
    origin_user_id_user integer,
    record_status integer,
    date_created timestamp(6) without time zone,
    date_modified timestamp(6) without time zone,
    phone_number character varying(15),
    password character varying(64),
    first_name character varying(100),
    surname character varying(100),
    cv_content character varying(1000),
    description character varying(30000),
    email character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 33613)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4775 (class 2604 OID 25136)
-- Name: refresh_token id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token ALTER COLUMN id SET DEFAULT nextval('public.refresh_token_id_seq'::regclass);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 219
-- Name: ability_id_ability_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ability_id_ability_seq', 1, false);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 221
-- Name: admin_id_admin_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_id_admin_seq', 1, false);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 224
-- Name: authentication_history_id_authentication_history_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authentication_history_id_authentication_history_seq', 1, false);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 226
-- Name: certificate_id_certificate_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.certificate_id_certificate_seq', 1, false);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 228
-- Name: country_id_country_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.country_id_country_seq', 1, false);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 232
-- Name: course_enrollment_id_course_enrollment_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_enrollment_id_course_enrollment_seq', 1, false);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 230
-- Name: course_id_course_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_id_course_seq', 1, false);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 234
-- Name: course_payment_history_id_payment_history_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_payment_history_id_payment_history_seq', 1, false);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 236
-- Name: course_progress_id_course_progress_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_progress_id_course_progress_seq', 1, false);


--
-- TOC entry 5099 (class 0 OID 0)
-- Dependencies: 238
-- Name: course_step_id_course_step_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_step_id_course_step_seq', 1, false);


--
-- TOC entry 5100 (class 0 OID 0)
-- Dependencies: 240
-- Name: course_type_id_course_type_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_type_id_course_type_seq', 1, false);


--
-- TOC entry 5101 (class 0 OID 0)
-- Dependencies: 242
-- Name: degree_id_degree_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.degree_id_degree_seq', 1, false);


--
-- TOC entry 5102 (class 0 OID 0)
-- Dependencies: 244
-- Name: domain_id_domain_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.domain_id_domain_seq', 1, false);


--
-- TOC entry 5103 (class 0 OID 0)
-- Dependencies: 247
-- Name: groups_id_group_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.groups_id_group_seq', 1, false);


--
-- TOC entry 5104 (class 0 OID 0)
-- Dependencies: 249
-- Name: language_id_language_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.language_id_language_seq', 1, false);


--
-- TOC entry 5105 (class 0 OID 0)
-- Dependencies: 251
-- Name: payment_category_id_payment_category_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_category_id_payment_category_seq', 1, false);


--
-- TOC entry 5106 (class 0 OID 0)
-- Dependencies: 253
-- Name: payment_mode_id_payment_mode_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_mode_id_payment_mode_seq', 1, false);


--
-- TOC entry 5107 (class 0 OID 0)
-- Dependencies: 255
-- Name: professional_skill_id_personal_skill_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.professional_skill_id_personal_skill_seq', 1, false);


--
-- TOC entry 5108 (class 0 OID 0)
-- Dependencies: 217
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 1, false);


--
-- TOC entry 5109 (class 0 OID 0)
-- Dependencies: 257
-- Name: sub_group_id_sub_group_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sub_group_id_sub_group_seq', 1, false);


--
-- TOC entry 5110 (class 0 OID 0)
-- Dependencies: 259
-- Name: university_id_university_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.university_id_university_seq', 1, false);


--
-- TOC entry 5111 (class 0 OID 0)
-- Dependencies: 263
-- Name: user_password_history_id_user_password_history_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_password_history_id_user_password_history_seq', 1, false);


--
-- TOC entry 5112 (class 0 OID 0)
-- Dependencies: 266
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_user_seq', 1, false);


--
-- TOC entry 4781 (class 2606 OID 33471)
-- Name: ability ability_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ability
    ADD CONSTRAINT ability_pkey PRIMARY KEY (id_ability);


--
-- TOC entry 4783 (class 2606 OID 33477)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id_admin);


--
-- TOC entry 4785 (class 2606 OID 33486)
-- Name: authentication_history authentication_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_history
    ADD CONSTRAINT authentication_history_pkey PRIMARY KEY (id_authentication_history);


--
-- TOC entry 4787 (class 2606 OID 33494)
-- Name: certificate certificate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT certificate_pkey PRIMARY KEY (id_certificate);


--
-- TOC entry 4789 (class 2606 OID 33500)
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id_country);


--
-- TOC entry 4793 (class 2606 OID 33514)
-- Name: course_enrollment course_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollment
    ADD CONSTRAINT course_enrollment_pkey PRIMARY KEY (id_course_enrollment);


--
-- TOC entry 4795 (class 2606 OID 33520)
-- Name: course_payment_history course_payment_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_payment_history
    ADD CONSTRAINT course_payment_history_pkey PRIMARY KEY (id_payment_history);


--
-- TOC entry 4791 (class 2606 OID 33508)
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id_course);


--
-- TOC entry 4797 (class 2606 OID 33526)
-- Name: course_progress course_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT course_progress_pkey PRIMARY KEY (id_course_progress);


--
-- TOC entry 4799 (class 2606 OID 33534)
-- Name: course_step course_step_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_step
    ADD CONSTRAINT course_step_pkey PRIMARY KEY (id_course_step);


--
-- TOC entry 4801 (class 2606 OID 33540)
-- Name: course_type course_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_type
    ADD CONSTRAINT course_type_pkey PRIMARY KEY (id_course_type);


--
-- TOC entry 4803 (class 2606 OID 33546)
-- Name: degree degree_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.degree
    ADD CONSTRAINT degree_pkey PRIMARY KEY (id_degree);


--
-- TOC entry 4805 (class 2606 OID 33552)
-- Name: domain domain_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domain
    ADD CONSTRAINT domain_pkey PRIMARY KEY (id_domain);


--
-- TOC entry 4807 (class 2606 OID 33561)
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id_group);


--
-- TOC entry 4809 (class 2606 OID 33567)
-- Name: language language_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT language_pkey PRIMARY KEY (id_language);


--
-- TOC entry 4811 (class 2606 OID 33573)
-- Name: payment_category payment_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_category
    ADD CONSTRAINT payment_category_pkey PRIMARY KEY (id_payment_category);


--
-- TOC entry 4813 (class 2606 OID 33579)
-- Name: payment_mode payment_mode_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_mode
    ADD CONSTRAINT payment_mode_pkey PRIMARY KEY (id_payment_mode);


--
-- TOC entry 4815 (class 2606 OID 33585)
-- Name: professional_skill professional_skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professional_skill
    ADD CONSTRAINT professional_skill_pkey PRIMARY KEY (id_personal_skill);


--
-- TOC entry 4777 (class 2606 OID 25138)
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4817 (class 2606 OID 33591)
-- Name: sub_group sub_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sub_group
    ADD CONSTRAINT sub_group_pkey PRIMARY KEY (id_sub_group);


--
-- TOC entry 4779 (class 2606 OID 25140)
-- Name: refresh_token uk_f95ixxe7pa48ryn1awmh2evt7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT uk_f95ixxe7pa48ryn1awmh2evt7 UNIQUE (user_id);


--
-- TOC entry 4819 (class 2606 OID 33597)
-- Name: university university_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university
    ADD CONSTRAINT university_pkey PRIMARY KEY (id_university);


--
-- TOC entry 4821 (class 2606 OID 33609)
-- Name: user_password_history user_password_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_password_history
    ADD CONSTRAINT user_password_history_pkey PRIMARY KEY (id_user_password_history);


--
-- TOC entry 4823 (class 2606 OID 33620)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4860 (class 2606 OID 33796)
-- Name: payment_category fk1g0n55utg2o52ng964fnmlmbg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_category
    ADD CONSTRAINT fk1g0n55utg2o52ng964fnmlmbg FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4885 (class 2606 OID 34096)
-- Name: user_sub_group fk1la8wt3w4te46qbhiev5wp075; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sub_group
    ADD CONSTRAINT fk1la8wt3w4te46qbhiev5wp075 FOREIGN KEY (id_sub_group) REFERENCES public.sub_group(id_sub_group);


--
-- TOC entry 4870 (class 2606 OID 33846)
-- Name: sub_group fk1oevv2ukitfslb3c8xg0jafsk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sub_group
    ADD CONSTRAINT fk1oevv2ukitfslb3c8xg0jafsk FOREIGN KEY (id_group) REFERENCES public.groups(id_group);


--
-- TOC entry 4855 (class 2606 OID 33781)
-- Name: domain fk2311bdb7yvgioq8duo94ii4hu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domain
    ADD CONSTRAINT fk2311bdb7yvgioq8duo94ii4hu FOREIGN KEY (origin_id_domain) REFERENCES public.domain(id_domain);


--
-- TOC entry 4842 (class 2606 OID 33706)
-- Name: course_progress fk2bscdlg61t51gb6y2hnwckds7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT fk2bscdlg61t51gb6y2hnwckds7 FOREIGN KEY (id_course) REFERENCES public.course(id_course);


--
-- TOC entry 4848 (class 2606 OID 33741)
-- Name: course_type fk2d5f1bjgw5fu5wgduu870psny; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_type
    ADD CONSTRAINT fk2d5f1bjgw5fu5wgduu870psny FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4871 (class 2606 OID 33856)
-- Name: university fk31t5wroe5uk132lymg44djuet; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university
    ADD CONSTRAINT fk31t5wroe5uk132lymg44djuet FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4825 (class 2606 OID 33626)
-- Name: admin_ability fk3g4fwqxt259jarnh97tpg35rf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_ability
    ADD CONSTRAINT fk3g4fwqxt259jarnh97tpg35rf FOREIGN KEY (admin_id) REFERENCES public.admin(id_admin);


--
-- TOC entry 4837 (class 2606 OID 33686)
-- Name: course_enrollment fk4fq8j4va3xa59eetxvm9lpadp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollment
    ADD CONSTRAINT fk4fq8j4va3xa59eetxvm9lpadp FOREIGN KEY (id_payment_mode) REFERENCES public.payment_mode(id_payment_mode);


--
-- TOC entry 4849 (class 2606 OID 33736)
-- Name: course_type fk4ftyun7f0a22b9cihg3c1unip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_type
    ADD CONSTRAINT fk4ftyun7f0a22b9cihg3c1unip FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4878 (class 2606 OID 33886)
-- Name: user_professional_skill fk4wot8w34qs65vew60nnywf5um; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_professional_skill
    ADD CONSTRAINT fk4wot8w34qs65vew60nnywf5um FOREIGN KEY (id_personal_skill) REFERENCES public.professional_skill(id_personal_skill);


--
-- TOC entry 4844 (class 2606 OID 33731)
-- Name: course_step fk784rrjnjqhw63csb3dftethhf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_step
    ADD CONSTRAINT fk784rrjnjqhw63csb3dftethhf FOREIGN KEY (origin_id_course_step) REFERENCES public.course_step(id_course_step);


--
-- TOC entry 4858 (class 2606 OID 33786)
-- Name: group_ability fk7livhsau7sjbnsnehl0r7d5rf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_ability
    ADD CONSTRAINT fk7livhsau7sjbnsnehl0r7d5rf FOREIGN KEY (ability_id) REFERENCES public.ability(id_ability);


--
-- TOC entry 4850 (class 2606 OID 33746)
-- Name: course_type fk81t4f64i5njs2ry1fh50f1kxw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_type
    ADD CONSTRAINT fk81t4f64i5njs2ry1fh50f1kxw FOREIGN KEY (origin_id_course_type) REFERENCES public.course_type(id_course_type);


--
-- TOC entry 4863 (class 2606 OID 33821)
-- Name: payment_mode fk84grtmymr7y8nhk1lhrakp922; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_mode
    ADD CONSTRAINT fk84grtmymr7y8nhk1lhrakp922 FOREIGN KEY (origin_id_payment_mode) REFERENCES public.payment_mode(id_payment_mode);


--
-- TOC entry 4851 (class 2606 OID 33751)
-- Name: degree fk8bynvhgly275pi9i96px2ywh1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.degree
    ADD CONSTRAINT fk8bynvhgly275pi9i96px2ywh1 FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4879 (class 2606 OID 33891)
-- Name: user_professional_skill fk96qxnbr1itptkisrwl20wcguu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_professional_skill
    ADD CONSTRAINT fk96qxnbr1itptkisrwl20wcguu FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4838 (class 2606 OID 33681)
-- Name: course_enrollment fkah1q2ck64vaynav9u1dibqcww; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollment
    ADD CONSTRAINT fkah1q2ck64vaynav9u1dibqcww FOREIGN KEY (id_course) REFERENCES public.course(id_course);


--
-- TOC entry 4827 (class 2606 OID 33631)
-- Name: authentication_history fkar7rtj06jn21q6vksjx8c6xyg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_history
    ADD CONSTRAINT fkar7rtj06jn21q6vksjx8c6xyg FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4867 (class 2606 OID 33836)
-- Name: professional_skill fkav9xx73jol5v7foj2bn1oemym; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professional_skill
    ADD CONSTRAINT fkav9xx73jol5v7foj2bn1oemym FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4861 (class 2606 OID 33801)
-- Name: payment_category fkb3c0ydwhttcb4ih563t20ka2u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_category
    ADD CONSTRAINT fkb3c0ydwhttcb4ih563t20ka2u FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4852 (class 2606 OID 33756)
-- Name: degree fkbfchu917m902b51k071kx94r5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.degree
    ADD CONSTRAINT fkbfchu917m902b51k071kx94r5 FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4833 (class 2606 OID 33666)
-- Name: course fkbgwv7efpe1s7r49aok1lps9nq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fkbgwv7efpe1s7r49aok1lps9nq FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4868 (class 2606 OID 33841)
-- Name: professional_skill fkc37llapkqqq71ktv7m5rg6osw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professional_skill
    ADD CONSTRAINT fkc37llapkqqq71ktv7m5rg6osw FOREIGN KEY (origin_id_personal_skill) REFERENCES public.professional_skill(id_personal_skill);


--
-- TOC entry 4834 (class 2606 OID 33661)
-- Name: course fkcqcp2i6bsj6wuk65w6faah8m3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fkcqcp2i6bsj6wuk65w6faah8m3 FOREIGN KEY (id_course_type) REFERENCES public.course_type(id_course_type);


--
-- TOC entry 4880 (class 2606 OID 33911)
-- Name: users fkdqhxjsg964hoy5rccylfod9r7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkdqhxjsg964hoy5rccylfod9r7 FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4864 (class 2606 OID 33811)
-- Name: payment_mode fkel8h8opv38ubpy7mxrjqvy6p5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_mode
    ADD CONSTRAINT fkel8h8opv38ubpy7mxrjqvy6p5 FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4840 (class 2606 OID 33696)
-- Name: course_payment_history fkeyvupvwwqdiai5u13g5gcjd0m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_payment_history
    ADD CONSTRAINT fkeyvupvwwqdiai5u13g5gcjd0m FOREIGN KEY (id_payment_mode) REFERENCES public.payment_mode(id_payment_mode);


--
-- TOC entry 4845 (class 2606 OID 33716)
-- Name: course_step fkfjdbrm4dauc55rigdyitqpg5w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_step
    ADD CONSTRAINT fkfjdbrm4dauc55rigdyitqpg5w FOREIGN KEY (id_course) REFERENCES public.course(id_course);


--
-- TOC entry 4862 (class 2606 OID 33806)
-- Name: payment_category fkg0ox6w5lnnk6659b5bhy8ya9u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_category
    ADD CONSTRAINT fkg0ox6w5lnnk6659b5bhy8ya9u FOREIGN KEY (origin_id_payment_category) REFERENCES public.payment_category(id_payment_category);


--
-- TOC entry 4856 (class 2606 OID 33771)
-- Name: domain fkgaatf6kg30abpi9yxsphuvb5n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domain
    ADD CONSTRAINT fkgaatf6kg30abpi9yxsphuvb5n FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4865 (class 2606 OID 33826)
-- Name: payment_mode fkgcchg45bc25xvo9h0hhwmltc8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_mode
    ADD CONSTRAINT fkgcchg45bc25xvo9h0hhwmltc8 FOREIGN KEY (id_payment_category) REFERENCES public.payment_category(id_payment_category);


--
-- TOC entry 4839 (class 2606 OID 33691)
-- Name: course_enrollment fkgmxu7mkwbbttdde2ti54xipgk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollment
    ADD CONSTRAINT fkgmxu7mkwbbttdde2ti54xipgk FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4841 (class 2606 OID 33701)
-- Name: course_payment_history fkh8t1ymm0u8krk9i3ua4v9he6v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_payment_history
    ADD CONSTRAINT fkh8t1ymm0u8krk9i3ua4v9he6v FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4857 (class 2606 OID 33776)
-- Name: domain fkhorlgk1kni2c08l2pxjev5x4q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domain
    ADD CONSTRAINT fkhorlgk1kni2c08l2pxjev5x4q FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4881 (class 2606 OID 33896)
-- Name: users fkisq57texvoxkgtw93qs568tap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkisq57texvoxkgtw93qs568tap FOREIGN KEY (id_country) REFERENCES public.country(id_country);


--
-- TOC entry 4886 (class 2606 OID 34101)
-- Name: user_sub_group fkjsvbh15vyvi8k6towfdlg83b6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sub_group
    ADD CONSTRAINT fkjsvbh15vyvi8k6towfdlg83b6 FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4824 (class 2606 OID 34088)
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id_user);


--
-- TOC entry 4875 (class 2606 OID 33876)
-- Name: user_degree fkjybabhhfb8m7qpimecttql0ec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_degree
    ADD CONSTRAINT fkjybabhhfb8m7qpimecttql0ec FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4828 (class 2606 OID 33636)
-- Name: certificate fkkpdjvh4bhhr1ndhe254v7f3iq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT fkkpdjvh4bhhr1ndhe254v7f3iq FOREIGN KEY (id_course) REFERENCES public.course(id_course);


--
-- TOC entry 4853 (class 2606 OID 33761)
-- Name: degree fkkqlfajo4t43x93qgws2x86otg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.degree
    ADD CONSTRAINT fkkqlfajo4t43x93qgws2x86otg FOREIGN KEY (origin_id_degree) REFERENCES public.degree(id_degree);


--
-- TOC entry 4835 (class 2606 OID 33671)
-- Name: course fkkyqo2c1ok7df8mpqoqxwxc6dl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fkkyqo2c1ok7df8mpqoqxwxc6dl FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4873 (class 2606 OID 33861)
-- Name: user_ability fkl8j7fnmuxam81vhgkret98b2q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ability
    ADD CONSTRAINT fkl8j7fnmuxam81vhgkret98b2q FOREIGN KEY (id_ability) REFERENCES public.ability(id_ability);


--
-- TOC entry 4869 (class 2606 OID 33831)
-- Name: professional_skill fkmdw42x9nvh9ch33ed0h9twk7j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professional_skill
    ADD CONSTRAINT fkmdw42x9nvh9ch33ed0h9twk7j FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4859 (class 2606 OID 33791)
-- Name: group_ability fkmkw35n0e3i9s5sqpfdy0bywn5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_ability
    ADD CONSTRAINT fkmkw35n0e3i9s5sqpfdy0bywn5 FOREIGN KEY (group_id) REFERENCES public.groups(id_group);


--
-- TOC entry 4846 (class 2606 OID 33721)
-- Name: course_step fkntg173dou4mpaows8y922fyrw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_step
    ADD CONSTRAINT fkntg173dou4mpaows8y922fyrw FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4877 (class 2606 OID 33881)
-- Name: user_password_history fko5dn5ojlceea60vnljuivr7wb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_password_history
    ADD CONSTRAINT fko5dn5ojlceea60vnljuivr7wb FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4882 (class 2606 OID 33916)
-- Name: users fkod9dreg4v67t3e10j063xs6v9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkod9dreg4v67t3e10j063xs6v9 FOREIGN KEY (origin_user_id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4883 (class 2606 OID 33906)
-- Name: users fkoqk961on232emmuhvx7m1s66n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkoqk961on232emmuhvx7m1s66n FOREIGN KEY (id_domain) REFERENCES public.domain(id_domain);


--
-- TOC entry 4830 (class 2606 OID 33651)
-- Name: country fkpd67em9wohwgqcyhmfrjrpxqw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT fkpd67em9wohwgqcyhmfrjrpxqw FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4826 (class 2606 OID 33621)
-- Name: admin_ability fkpkryetkx21crny5cvrxvde5g5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_ability
    ADD CONSTRAINT fkpkryetkx21crny5cvrxvde5g5 FOREIGN KEY (ability_id) REFERENCES public.ability(id_ability);


--
-- TOC entry 4831 (class 2606 OID 33646)
-- Name: country fkpsv3w7st0yk26mrppv970heow; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT fkpsv3w7st0yk26mrppv970heow FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4832 (class 2606 OID 33656)
-- Name: country fkqimplx5mk3i5wdd73b4b5vb50; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT fkqimplx5mk3i5wdd73b4b5vb50 FOREIGN KEY (origin_id_country) REFERENCES public.country(id_country);


--
-- TOC entry 4854 (class 2606 OID 33766)
-- Name: degree fkqk0qmtpg04wmnxps472uly8c0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.degree
    ADD CONSTRAINT fkqk0qmtpg04wmnxps472uly8c0 FOREIGN KEY (id_university) REFERENCES public.university(id_university);


--
-- TOC entry 4847 (class 2606 OID 33726)
-- Name: course_step fkqn7ydvltjpdur5iagpcb4824t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_step
    ADD CONSTRAINT fkqn7ydvltjpdur5iagpcb4824t FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4829 (class 2606 OID 33641)
-- Name: certificate fkqo3vp6hlcpjyr91hn5j3t9sod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT fkqo3vp6hlcpjyr91hn5j3t9sod FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4884 (class 2606 OID 33901)
-- Name: users fkqshsex43hnkko2qqswywx7nc9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkqshsex43hnkko2qqswywx7nc9 FOREIGN KEY (id_admin) REFERENCES public.admin(id_admin);


--
-- TOC entry 4843 (class 2606 OID 33711)
-- Name: course_progress fkr9efjhx2w1t32nub3jsf76xro; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT fkr9efjhx2w1t32nub3jsf76xro FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4876 (class 2606 OID 33871)
-- Name: user_degree fkrfi71utq4qkx5l57abk69rrj7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_degree
    ADD CONSTRAINT fkrfi71utq4qkx5l57abk69rrj7 FOREIGN KEY (id_degree) REFERENCES public.degree(id_degree);


--
-- TOC entry 4872 (class 2606 OID 33851)
-- Name: university fks0cjihbkovo08yk739vqccpmx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university
    ADD CONSTRAINT fks0cjihbkovo08yk739vqccpmx FOREIGN KEY (country) REFERENCES public.country(id_country);


--
-- TOC entry 4874 (class 2606 OID 33866)
-- Name: user_ability fksv1r7p2fc6v1dard145d2lakk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ability
    ADD CONSTRAINT fksv1r7p2fc6v1dard145d2lakk FOREIGN KEY (id_user) REFERENCES public.users(id_user);


--
-- TOC entry 4866 (class 2606 OID 33816)
-- Name: payment_mode fktr58cknan2e97hy6bui5odowb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_mode
    ADD CONSTRAINT fktr58cknan2e97hy6bui5odowb FOREIGN KEY (id_language) REFERENCES public.language(id_language);


--
-- TOC entry 4836 (class 2606 OID 33676)
-- Name: course fkunklaos8b09gbt3gkp9feyc3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fkunklaos8b09gbt3gkp9feyc3 FOREIGN KEY (origin_id_course) REFERENCES public.course(id_course);
