-- public.ability definition

-- Drop table

-- DROP TABLE public.ability;

CREATE TABLE public.ability (
	id_ability int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ability_name varchar(50) NULL,
	record_status int4 NULL,
	CONSTRAINT ability_pkey PRIMARY KEY (id_ability)
);


-- public."admin" definition

-- Drop table

-- DROP TABLE public."admin";

CREATE TABLE public."admin" (
	id_admin serial4 NOT NULL,
	"password" varchar(64) NULL,
	username varchar(100) NULL,
	CONSTRAINT admin_pkey PRIMARY KEY (id_admin)
);


-- public."groups" definition

-- Drop table

-- DROP TABLE public."groups";

CREATE TABLE public."groups" (
	id_group serial4 NOT NULL,
	group_name varchar(100) NULL,
	record_status int4 NULL,
	CONSTRAINT groups_pkey PRIMARY KEY (id_group)
);


-- public."language" definition

-- Drop table

-- DROP TABLE public."language";

CREATE TABLE public."language" (
	id_language serial4 NOT NULL,
	language_code varchar(2) NULL,
	language_name varchar(85) NULL,
	CONSTRAINT language_pkey PRIMARY KEY (id_language)
);


-- public.pending_user_registration definition

-- Drop table

-- DROP TABLE public.pending_user_registration;

CREATE TABLE public.pending_user_registration (
	id serial4 NOT NULL,
	email varchar(255) NULL,
	expires_at timestamp NOT NULL,
	firstname varchar(255) NULL,
	lastname varchar(255) NULL,
	otp varchar(255) NULL,
	"password" varchar(255) NULL,
	CONSTRAINT pending_user_registration_pkey PRIMARY KEY (id)
);


-- public.admin_ability definition

-- Drop table

-- DROP TABLE public.admin_ability;

CREATE TABLE public.admin_ability (
	admin_id int4 NOT NULL,
	ability_id int4 NOT NULL,
	CONSTRAINT fk3g4fwqxt259jarnh97tpg35rf FOREIGN KEY (admin_id) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkpkryetkx21crny5cvrxvde5g5 FOREIGN KEY (ability_id) REFERENCES public.ability(id_ability)
);


-- public.country definition

-- Drop table

-- DROP TABLE public.country;

CREATE TABLE public.country (
	id_country serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_country int4 NULL,
	country_name varchar(100) NULL,
	CONSTRAINT country_pkey PRIMARY KEY (id_country),
	CONSTRAINT fkpd67em9wohwgqcyhmfrjrpxqw FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkpsv3w7st0yk26mrppv970heow FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkqimplx5mk3i5wdd73b4b5vb50 FOREIGN KEY (origin_id_country) REFERENCES public.country(id_country)
);


-- public.course_type definition

-- Drop table

-- DROP TABLE public.course_type;

CREATE TABLE public.course_type (
	id_course_type serial4 NOT NULL,
	course_type_name varchar(100) NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	record_status int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_course_type int4 NULL,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT course_type_pkey PRIMARY KEY (id_course_type),
	CONSTRAINT fk2d5f1bjgw5fu5wgduu870psny FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fk4ftyun7f0a22b9cihg3c1unip FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fk81t4f64i5njs2ry1fh50f1kxw FOREIGN KEY (origin_id_course_type) REFERENCES public.course_type(id_course_type)
);


-- public."domain" definition

-- Drop table

-- DROP TABLE public."domain";

CREATE TABLE public."domain" (
	id_domain serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	domain_name varchar(100) NULL,
	record_status int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_domain int4 NULL,
	CONSTRAINT domain_pkey PRIMARY KEY (id_domain),
	CONSTRAINT fk2311bdb7yvgioq8duo94ii4hu FOREIGN KEY (origin_id_domain) REFERENCES public."domain"(id_domain),
	CONSTRAINT fkgaatf6kg30abpi9yxsphuvb5n FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkhorlgk1kni2c08l2pxjev5x4q FOREIGN KEY (id_language) REFERENCES public."language"(id_language)
);


-- public.group_ability definition

-- Drop table

-- DROP TABLE public.group_ability;

CREATE TABLE public.group_ability (
	group_id int4 NOT NULL,
	ability_id int4 NOT NULL,
	CONSTRAINT fkmkw35n0e3i9s5sqpfdy0bywn5 FOREIGN KEY (group_id) REFERENCES public."groups"(id_group)
);


-- public.payment_category definition

-- Drop table

-- DROP TABLE public.payment_category;

CREATE TABLE public.payment_category (
	id_payment_category serial4 NOT NULL,
	category_name varchar(100) NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	record_status int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_payment_category int4 NULL,
	CONSTRAINT payment_category_pkey PRIMARY KEY (id_payment_category),
	CONSTRAINT fk1g0n55utg2o52ng964fnmlmbg FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkb3c0ydwhttcb4ih563t20ka2u FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkg0ox6w5lnnk6659b5bhy8ya9u FOREIGN KEY (origin_id_payment_category) REFERENCES public.payment_category(id_payment_category)
);


-- public.payment_mode definition

-- Drop table

-- DROP TABLE public.payment_mode;

CREATE TABLE public.payment_mode (
	id_payment_mode serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	mode_code varchar(50) NULL,
	mode_name varchar(255) NULL,
	record_status int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_payment_mode int4 NULL,
	id_payment_category int4 NULL,
	CONSTRAINT payment_mode_pkey PRIMARY KEY (id_payment_mode),
	CONSTRAINT fk84grtmymr7y8nhk1lhrakp922 FOREIGN KEY (origin_id_payment_mode) REFERENCES public.payment_mode(id_payment_mode),
	CONSTRAINT fkel8h8opv38ubpy7mxrjqvy6p5 FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkgcchg45bc25xvo9h0hhwmltc8 FOREIGN KEY (id_payment_category) REFERENCES public.payment_category(id_payment_category),
	CONSTRAINT fktr58cknan2e97hy6bui5odowb FOREIGN KEY (id_language) REFERENCES public."language"(id_language)
);


-- public.personal_skill definition

-- Drop table

-- DROP TABLE public.personal_skill;

CREATE TABLE public.personal_skill (
	id_personal_skill serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	record_status int4 NULL,
	skill_name varchar(255) NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_personal_skill int4 NULL,
	CONSTRAINT personal_skill_pkey PRIMARY KEY (id_personal_skill),
	CONSTRAINT fkbn5em2cxh7a1x8o8a1avdlwvu FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkmph1k9aerlvg0y7d8ee6ve6g FOREIGN KEY (origin_id_personal_skill) REFERENCES public.personal_skill(id_personal_skill),
	CONSTRAINT fkqqjis07onhl7opwc32qdrw8sj FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin)
);


-- public.professional_skill definition

-- Drop table

-- DROP TABLE public.professional_skill;

CREATE TABLE public.professional_skill (
	id_personal_skill int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_created timestamp(6) NULL,
	date_modified timestamp(6) NULL,
	record_status int4 NULL,
	skill_name varchar(100) NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_personal_skill int4 NULL,
	CONSTRAINT professional_skill_pkey PRIMARY KEY (id_personal_skill),
	CONSTRAINT fkav9xx73jol5v7foj2bn1oemym FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkc37llapkqqq71ktv7m5rg6osw FOREIGN KEY (origin_id_personal_skill) REFERENCES public.professional_skill(id_personal_skill),
	CONSTRAINT fkmdw42x9nvh9ch33ed0h9twk7j FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin)
);


-- public.sub_group definition

-- Drop table

-- DROP TABLE public.sub_group;

CREATE TABLE public.sub_group (
	id_sub_group serial4 NOT NULL,
	record_status int4 NULL,
	sub_group_name varchar(100) NULL,
	id_group int4 NULL,
	CONSTRAINT sub_group_pkey PRIMARY KEY (id_sub_group),
	CONSTRAINT fk1oevv2ukitfslb3c8xg0jafsk FOREIGN KEY (id_group) REFERENCES public."groups"(id_group)
);


-- public.subgroup_ability definition

-- Drop table

-- DROP TABLE public.subgroup_ability;

CREATE TABLE public.subgroup_ability (
	subgroup_id int4 NOT NULL,
	ability_id int4 NOT NULL,
	CONSTRAINT fkf07lbuclrmjnsc8sfvt5s91cp FOREIGN KEY (ability_id) REFERENCES public.ability(id_ability),
	CONSTRAINT fkmgpnbft8dj6qdyh47admel406 FOREIGN KEY (subgroup_id) REFERENCES public.sub_group(id_sub_group)
);


-- public.university definition

-- Drop table

-- DROP TABLE public.university;

CREATE TABLE public.university (
	id_university serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	record_status int4 NULL,
	university_name varchar(100) NULL,
	country int4 NULL,
	id_admin int4 NULL,
	CONSTRAINT university_pkey PRIMARY KEY (id_university),
	CONSTRAINT fk31t5wroe5uk132lymg44djuet FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fks0cjihbkovo08yk739vqccpmx FOREIGN KEY (country) REFERENCES public.country(id_country)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id_user serial4 NOT NULL,
	cv_content varchar(1000) NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	description varchar(30000) NULL,
	email varchar(255) NULL,
	first_name varchar(100) NULL,
	"password" varchar(64) NULL,
	phone_number varchar(15) NULL,
	record_status int4 NULL,
	surname varchar(100) NULL,
	id_country int4 NULL,
	id_admin int4 NULL,
	id_domain int4 NULL,
	id_language int4 NULL,
	origin_user_id_user int4 NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id_user),
	CONSTRAINT fkdqhxjsg964hoy5rccylfod9r7 FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkisq57texvoxkgtw93qs568tap FOREIGN KEY (id_country) REFERENCES public.country(id_country),
	CONSTRAINT fkod9dreg4v67t3e10j063xs6v9 FOREIGN KEY (origin_user_id_user) REFERENCES public.users(id_user),
	CONSTRAINT fkoqk961on232emmuhvx7m1s66n FOREIGN KEY (id_domain) REFERENCES public."domain"(id_domain),
	CONSTRAINT fkqshsex43hnkko2qqswywx7nc9 FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin)
);


-- public.authentication_history definition

-- Drop table

-- DROP TABLE public.authentication_history;

CREATE TABLE public.authentication_history (
	id_authentication_history serial4 NOT NULL,
	authentication_status int4 NULL,
	date_authentication timestamp NULL,
	id_user int4 NULL,
	CONSTRAINT authentication_history_pkey PRIMARY KEY (id_authentication_history),
	CONSTRAINT fkar7rtj06jn21q6vksjx8c6xyg FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.course definition

-- Drop table

-- DROP TABLE public.course;

CREATE TABLE public.course (
	id_course serial4 NOT NULL,
	course_title varchar(100) NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	description varchar(30000) NULL,
	photo varchar(1000) NULL,
	price float8 NULL,
	record_status int4 NULL,
	id_course_type int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_course int4 NULL,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT course_pkey PRIMARY KEY (id_course),
	CONSTRAINT fkbgwv7efpe1s7r49aok1lps9nq FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkcqcp2i6bsj6wuk65w6faah8m3 FOREIGN KEY (id_course_type) REFERENCES public.course_type(id_course_type),
	CONSTRAINT fkkyqo2c1ok7df8mpqoqxwxc6dl FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkunklaos8b09gbt3gkp9feyc3 FOREIGN KEY (origin_id_course) REFERENCES public.course(id_course)
);


-- public.course_enrollment definition

-- Drop table

-- DROP TABLE public.course_enrollment;

CREATE TABLE public.course_enrollment (
	id_course_enrollment serial4 NOT NULL,
	record_status int4 NULL,
	total_paid float8 NULL,
	id_course int4 NULL,
	id_payment_mode int4 NULL,
	id_user int4 NULL,
	CONSTRAINT course_enrollment_pkey PRIMARY KEY (id_course_enrollment),
	CONSTRAINT fk4fq8j4va3xa59eetxvm9lpadp FOREIGN KEY (id_payment_mode) REFERENCES public.payment_mode(id_payment_mode),
	CONSTRAINT fkah1q2ck64vaynav9u1dibqcww FOREIGN KEY (id_course) REFERENCES public.course(id_course),
	CONSTRAINT fkgmxu7mkwbbttdde2ti54xipgk FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.course_payment_history definition

-- Drop table

-- DROP TABLE public.course_payment_history;

CREATE TABLE public.course_payment_history (
	id_payment_history serial4 NOT NULL,
	amount_paid float8 NULL,
	payment_date timestamp NULL,
	record_status int4 NULL,
	id_payment_mode int4 NULL,
	id_user int4 NULL,
	CONSTRAINT course_payment_history_pkey PRIMARY KEY (id_payment_history),
	CONSTRAINT fkeyvupvwwqdiai5u13g5gcjd0m FOREIGN KEY (id_payment_mode) REFERENCES public.payment_mode(id_payment_mode),
	CONSTRAINT fkh8t1ymm0u8krk9i3ua4v9he6v FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.course_progress definition

-- Drop table

-- DROP TABLE public.course_progress;

CREATE TABLE public.course_progress (
	id_course_progress serial4 NOT NULL,
	completion_level float8 NULL,
	id_course int4 NULL,
	id_user int4 NULL,
	course_id int4 NULL,
	user_id int4 NULL,
	CONSTRAINT course_progress_pkey PRIMARY KEY (id_course_progress),
	CONSTRAINT fk2bscdlg61t51gb6y2hnwckds7 FOREIGN KEY (id_course) REFERENCES public.course(id_course),
	CONSTRAINT fkmootcccgd4bqe8cjtma7stkp1 FOREIGN KEY (user_id) REFERENCES public.users(id_user),
	CONSTRAINT fkr9efjhx2w1t32nub3jsf76xro FOREIGN KEY (id_user) REFERENCES public.users(id_user),
	CONSTRAINT fkrc6owopnnsws5xddrk2bsjpee FOREIGN KEY (course_id) REFERENCES public.course(id_course)
);


-- public.course_step definition

-- Drop table

-- DROP TABLE public.course_step;

CREATE TABLE public.course_step (
	id_course_step serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	description varchar(30000) NULL,
	file_content varchar(1000) NULL,
	record_status int4 NULL,
	step_order int4 NULL,
	id_course int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_course_step int4 NULL,
	CONSTRAINT course_step_pkey PRIMARY KEY (id_course_step),
	CONSTRAINT fk784rrjnjqhw63csb3dftethhf FOREIGN KEY (origin_id_course_step) REFERENCES public.course_step(id_course_step),
	CONSTRAINT fkfjdbrm4dauc55rigdyitqpg5w FOREIGN KEY (id_course) REFERENCES public.course(id_course),
	CONSTRAINT fkntg173dou4mpaows8y922fyrw FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkqn7ydvltjpdur5iagpcb4824t FOREIGN KEY (id_language) REFERENCES public."language"(id_language)
);


-- public."degree" definition

-- Drop table

-- DROP TABLE public."degree";

CREATE TABLE public."degree" (
	id_degree serial4 NOT NULL,
	date_created timestamp NULL,
	date_modified timestamp NULL,
	degree_name varchar(100) NULL,
	record_status int4 NULL,
	id_admin int4 NULL,
	id_language int4 NULL,
	origin_id_degree int4 NULL,
	id_university int4 NULL,
	CONSTRAINT degree_pkey PRIMARY KEY (id_degree),
	CONSTRAINT fk8bynvhgly275pi9i96px2ywh1 FOREIGN KEY (id_admin) REFERENCES public."admin"(id_admin),
	CONSTRAINT fkbfchu917m902b51k071kx94r5 FOREIGN KEY (id_language) REFERENCES public."language"(id_language),
	CONSTRAINT fkkqlfajo4t43x93qgws2x86otg FOREIGN KEY (origin_id_degree) REFERENCES public."degree"(id_degree),
	CONSTRAINT fkqk0qmtpg04wmnxps472uly8c0 FOREIGN KEY (id_university) REFERENCES public.university(id_university)
);


-- public.refresh_token definition

-- Drop table

-- DROP TABLE public.refresh_token;

CREATE TABLE public.refresh_token (
	id serial4 NOT NULL,
	expires_at timestamp NOT NULL,
	"token" varchar(255) NULL,
	user_id int4 NULL,
	CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
	CONSTRAINT uk_f95ixxe7pa48ryn1awmh2evt7 UNIQUE (user_id),
	CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id_user)
);


-- public.user_ability definition

-- Drop table

-- DROP TABLE public.user_ability;

CREATE TABLE public.user_ability (
	id_user int4 NOT NULL,
	id_ability int4 NOT NULL,
	CONSTRAINT user_ability_pkey PRIMARY KEY (id_user, id_ability),
	CONSTRAINT fkl8j7fnmuxam81vhgkret98b2q FOREIGN KEY (id_ability) REFERENCES public.ability(id_ability),
	CONSTRAINT fksv1r7p2fc6v1dard145d2lakk FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.user_degree definition

-- Drop table

-- DROP TABLE public.user_degree;

CREATE TABLE public.user_degree (
	id_user int4 NOT NULL,
	id_degree int4 NOT NULL,
	CONSTRAINT fkjybabhhfb8m7qpimecttql0ec FOREIGN KEY (id_user) REFERENCES public.users(id_user),
	CONSTRAINT fkrfi71utq4qkx5l57abk69rrj7 FOREIGN KEY (id_degree) REFERENCES public."degree"(id_degree)
);


-- public.user_password_history definition

-- Drop table

-- DROP TABLE public.user_password_history;

CREATE TABLE public.user_password_history (
	id_user_password_history serial4 NOT NULL,
	date_audded_to_history timestamp NULL,
	"password" varchar(255) NULL,
	id_user int4 NULL,
	date_added_to_history timestamp(6) NULL,
	CONSTRAINT user_password_history_pkey PRIMARY KEY (id_user_password_history),
	CONSTRAINT fko5dn5ojlceea60vnljuivr7wb FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.user_professional_skill definition

-- Drop table

-- DROP TABLE public.user_professional_skill;

CREATE TABLE public.user_professional_skill (
	id_user int4 NOT NULL,
	id_personal_skill int4 NOT NULL,
	CONSTRAINT fk4wot8w34qs65vew60nnywf5um FOREIGN KEY (id_personal_skill) REFERENCES public.professional_skill(id_personal_skill),
	CONSTRAINT fk96qxnbr1itptkisrwl20wcguu FOREIGN KEY (id_user) REFERENCES public.users(id_user),
	CONSTRAINT fkaa08808t3ngurlvb7g4ps6s46 FOREIGN KEY (id_personal_skill) REFERENCES public.personal_skill(id_personal_skill)
);


-- public.user_sub_group definition

-- Drop table

-- DROP TABLE public.user_sub_group;

CREATE TABLE public.user_sub_group (
	id_user int4 NOT NULL,
	id_sub_group int4 NOT NULL,
	CONSTRAINT fk1la8wt3w4te46qbhiev5wp075 FOREIGN KEY (id_sub_group) REFERENCES public.sub_group(id_sub_group),
	CONSTRAINT fkjsvbh15vyvi8k6towfdlg83b6 FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.user_subgroup definition

-- Drop table

-- DROP TABLE public.user_subgroup;

CREATE TABLE public.user_subgroup (
	id_user int4 NOT NULL,
	id_subgroup int4 NOT NULL,
	CONSTRAINT user_subgroup_pkey PRIMARY KEY (id_user, id_subgroup),
	CONSTRAINT fk4m5shq7hipm7d35bcmmfs0c9y FOREIGN KEY (id_subgroup) REFERENCES public.sub_group(id_sub_group),
	CONSTRAINT fkq76wbv6x9arl6esq5oyv0lya9 FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- public.certificate definition

-- Drop table

-- DROP TABLE public.certificate;

CREATE TABLE public.certificate (
	id_certificate serial4 NOT NULL,
	"content" varchar(1000) NULL,
	id_course int4 NULL,
	id_user int4 NULL,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	record_status int4 NULL,
	CONSTRAINT certificate_pkey PRIMARY KEY (id_certificate),
	CONSTRAINT fkkpdjvh4bhhr1ndhe254v7f3iq FOREIGN KEY (id_course) REFERENCES public.course(id_course),
	CONSTRAINT fkqo3vp6hlcpjyr91hn5j3t9sod FOREIGN KEY (id_user) REFERENCES public.users(id_user)
);


-- Module d'auto-diagnostic

-- Table des diagnostics (types de tests)
CREATE TABLE public.diagnostic (
    id_diagnostic serial4 NOT NULL,
    diagnostic_name varchar(255) NOT NULL,
    description text NULL,
    is_active boolean DEFAULT true,
    max_duration_minutes int4 NULL,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255) NULL,
    updated_at timestamp(6) NULL,
    updated_by varchar(255) NULL,
    CONSTRAINT diagnostic_pkey PRIMARY KEY (id_diagnostic)
);

-- Table des domaines/catégories de questions
CREATE TABLE public.diagnostic_domain (
    id_domain serial4 NOT NULL,
    domain_name varchar(255) NOT NULL,
    domain_code varchar(50) NOT NULL,
    weight_factor float8 DEFAULT 1.0,
    id_diagnostic int4 NOT NULL,
    CONSTRAINT diagnostic_domain_pkey PRIMARY KEY (id_domain),
    CONSTRAINT fk_domain_diagnostic FOREIGN KEY (id_diagnostic) REFERENCES public.diagnostic(id_diagnostic)
);

-- Table des questions
CREATE TABLE public.diagnostic_question (
    id_question serial4 NOT NULL,
    question_text text NOT NULL,
    question_type varchar(50) NOT NULL, -- SINGLE_CHOICE, MULTIPLE_CHOICE, SCALE, TEXT
    question_order int4 NOT NULL,
    is_required boolean DEFAULT true,
    weight float8 DEFAULT 1.0,
    id_domain int4 NOT NULL,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT diagnostic_question_pkey PRIMARY KEY (id_question),
    CONSTRAINT fk_question_domain FOREIGN KEY (id_domain) REFERENCES public.diagnostic_domain(id_domain)
);

-- Table des options de réponse
CREATE TABLE public.diagnostic_answer_option (
    id_option serial4 NOT NULL,
    option_text varchar(500) NOT NULL,
    option_value float8 NOT NULL, -- Score/pondération de cette option
    option_order int4 NOT NULL,
    id_question int4 NOT NULL,
    CONSTRAINT diagnostic_answer_option_pkey PRIMARY KEY (id_option),
    CONSTRAINT fk_option_question FOREIGN KEY (id_question) REFERENCES public.diagnostic_question(id_question)
);

-- Table des sessions de diagnostic (historique)
CREATE TABLE public.diagnostic_session (
    id_session serial4 NOT NULL,
    session_uuid varchar(255) UNIQUE NOT NULL,
    id_user int4 NULL, -- Peut être NULL pour utilisateurs anonymes
    id_diagnostic int4 NOT NULL,
    status varchar(50) DEFAULT 'IN_PROGRESS', -- IN_PROGRESS, COMPLETED, ABANDONED
    started_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp(6) NULL,
    total_score float8 NULL,
    result_profile varchar(255) NULL,
    CONSTRAINT diagnostic_session_pkey PRIMARY KEY (id_session),
    CONSTRAINT fk_session_user FOREIGN KEY (id_user) REFERENCES public.users(id_user),
    CONSTRAINT fk_session_diagnostic FOREIGN KEY (id_diagnostic) REFERENCES public.diagnostic(id_diagnostic)
);

-- Table des réponses utilisateur
CREATE TABLE public.diagnostic_user_answer (
    id_answer serial4 NOT NULL,
    id_session int4 NOT NULL,
    id_question int4 NOT NULL,
    id_option int4 NULL, -- NULL pour questions texte
    text_answer text NULL, -- Pour questions ouvertes
    numeric_answer float8 NULL, -- Pour échelles
    answered_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT diagnostic_user_answer_pkey PRIMARY KEY (id_answer),
    CONSTRAINT fk_answer_session FOREIGN KEY (id_session) REFERENCES public.diagnostic_session(id_session),
    CONSTRAINT fk_answer_question FOREIGN KEY (id_question) REFERENCES public.diagnostic_question(id_question),
    CONSTRAINT fk_answer_option FOREIGN KEY (id_option) REFERENCES public.diagnostic_answer_option(id_option)
);

-- Table des scores par domaine
CREATE TABLE public.diagnostic_domain_score (
    id_domain_score serial4 NOT NULL,
    id_session int4 NOT NULL,
    id_domain int4 NOT NULL,
    raw_score float8 NOT NULL,
    weighted_score float8 NOT NULL,
    percentage float8 NOT NULL,
    CONSTRAINT diagnostic_domain_score_pkey PRIMARY KEY (id_domain_score),
    CONSTRAINT fk_score_session FOREIGN KEY (id_session) REFERENCES public.diagnostic_session(id_session),
    CONSTRAINT fk_score_domain FOREIGN KEY (id_domain) REFERENCES public.diagnostic_domain(id_domain)
);

-- Table des profils/résultats
CREATE TABLE public.diagnostic_result_profile (
    id_profile serial4 NOT NULL,
    profile_name varchar(255) NOT NULL,
    profile_code varchar(50) NOT NULL,
    description text NULL,
    min_score float8 NOT NULL,
    max_score float8 NOT NULL,
    recommendations text NULL,
    id_diagnostic int4 NOT NULL,
    CONSTRAINT diagnostic_result_profile_pkey PRIMARY KEY (id_profile),
    CONSTRAINT fk_profile_diagnostic FOREIGN KEY (id_diagnostic) REFERENCES public.diagnostic(id_diagnostic)
);

-- ===================================
-- FAIR-006: Table pour le système d'upload et de gestion des fichiers
-- ===================================

CREATE TABLE public.file_upload (
    id_file serial4 NOT NULL,
    original_name varchar(255) NOT NULL,
    generated_name varchar(255) NOT NULL UNIQUE,
    file_size int8 NOT NULL,
    file_type varchar(50) NOT NULL, -- PDF, PPTX, MP4, MOV, AVI, PNG, JPG
    mime_type varchar(100) NOT NULL,
    file_extension varchar(10) NOT NULL,
    upload_path varchar(500) NOT NULL, -- Chemin complet du fichier
    uploaded_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    uploaded_by_user int4 NULL,
    is_public boolean DEFAULT false,
    access_url varchar(500) NULL, -- URL publique d'accès
    description varchar(1000) NULL,
    record_status int4 DEFAULT 1, -- 1=Actif, 0=Supprimé
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255) NULL,
    updated_at timestamp(6) NULL,
    updated_by varchar(255) NULL,
    CONSTRAINT file_upload_pkey PRIMARY KEY (id_file),
    CONSTRAINT uk_file_generated_name UNIQUE (generated_name),
    CONSTRAINT fk_file_user FOREIGN KEY (uploaded_by_user) REFERENCES public.users(id_user)
);

-- Index pour améliorer les performances des requêtes
CREATE INDEX idx_file_upload_user ON public.file_upload(uploaded_by_user);
CREATE INDEX idx_file_upload_type ON public.file_upload(file_type);
CREATE INDEX idx_file_upload_status ON public.file_upload(record_status);
CREATE INDEX idx_file_upload_date ON public.file_upload(uploaded_at);

-- Commentaires sur les colonnes pour FAIR-006
COMMENT ON TABLE public.file_upload IS 'Table de gestion des fichiers uploadés - FAIR-006';
COMMENT ON COLUMN public.file_upload.original_name IS 'Nom original du fichier tel qu''uploadé par l''utilisateur';
COMMENT ON COLUMN public.file_upload.generated_name IS 'Nom généré selon le format [timestamp]_[uuid].extension';
COMMENT ON COLUMN public.file_upload.file_size IS 'Taille du fichier en octets';
COMMENT ON COLUMN public.file_upload.file_type IS 'Type de fichier (PDF, PPTX, MP4, MOV, AVI, PNG, JPG)';
COMMENT ON COLUMN public.file_upload.upload_path IS 'Chemin complet du fichier sur le serveur (/var/app/uploads/...)';
COMMENT ON COLUMN public.file_upload.access_url IS 'URL publique d''accès au fichier (base_url + generated_name)';
COMMENT ON COLUMN public.file_upload.is_public IS 'Indique si le fichier est accessible publiquement';
COMMENT ON COLUMN public.file_upload.record_status IS '1=Actif, 0=Supprimé (soft delete)';